name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch full history (non-shallow), otherwise diff will only know about last commit
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install Python
        run: |
          pip install nbconvert
      - name: nbconvert
        run: |
          files_changed=$(git diff --diff-filter=ACMRT --name-only -r ${{ github.event.before }} ${{ github.sha }}) # filter add/change/etc files; between last pushed commit and current commit (pushes can contain more than one commit)
          for file in $files_changed; do # TODO: auto update README.md with TOC of files
            if [[ $file =~ .*\.ipynb$ ]]; then
              jupyter nbconvert --to html $file # TODO: --output-dir static/notebooks/
              git add "${file%.*}".html
            fi
          done # TODO: clean up removed files
      - name: Commit report
        run: |
          git config --global user.name 'Jonathan Mettes'
          git config --global user.email 'jmettes@users.noreply.github.com'
          git diff --quiet && git diff --staged --quiet || git commit -m "Automatic nbconvert" && git push # only commit/push of changes
