name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install Python
        run: |
          pip install nbconvert
      - name: Create report file
        run: |
          files_changed=$(git diff --diff-filter=ACMRT --name-only -r ${{ github.event.before }} ${{ github.sha }})
          for file in $files_changed; do
            if [[ $file =~ .*\.ipynb$ ]]; then
              nbconvert --to markdown $file
              git add $file
            fi
          done 
      - name: Commit report
        run: |
          git config --global user.name 'Jonathan Mettes'
          git config --global user.email 'jmettes@users.noreply.github.com'
          git commit -am "Automatic nbconvert"
          git push
