name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: |
          count=(jq --raw-output '.commits | length' "$GITHUB_EVENT_PATH")
          git fetch --depth=$count origin
          files_changed=$(git diff --name-only -r ${{ github.event.before }} ${{ github.sha }})
          for file in $files_changed; do echo - $file >> report.txt; done 
      - name: Commit report
        run: |
          git config --global user.name 'Jonathan Mettes'
          git config --global user.email 'jmettes@users.noreply.github.com'
          git add report.txt
          git commit -am "Automated report"
          git push
